monolog:
    handlers:
        filter_for_errors:
            type: fingers_crossed
            # if *one* log is error or higher, pass *all* to file_log
            action_level: error
            handler: error

        # now passed *all* logs, but only if one log is error or higher
        error:
            type: stream
            path: "%kernel.logs_dir%/error.log"

        security:
            type: rotating_file
            path: "%kernel.logs_dir%/security.log"
            level: info
            channels: [security]
            max_files: 10
            
        request:
            type: rotating_file
            path: "%kernel.logs_dir%/request.log"
            level: info
            channels: [request]
            max_files: 10
            